- name: my fisrt web server
  hosts: all
  become: true
  tasks:
    - name: install webserver
      yum:
        name: httpd
        state: latest

    - name: start httpd daemom
      service: 
        state: started
        name: httpd
        enabled: true
        
